INSERT INTO fields(id, description) VALUES('IA00', 'energetické auditorství');
--;;
INSERT INTO fields(id, description) VALUES('ID00', 'dopravní stavby');
--;;
INSERT INTO fields(id, description) VALUES('IE00', 'technika prostředí staveb');
--;;
INSERT INTO fields(id, description) VALUES('IE01', 'technika prostředí staveb - technická zařízení');
--;;
INSERT INTO fields(id, description) VALUES('IE02', 'technika prostředí staveb - elektrotechnická zařízení');
--;;
INSERT INTO fields(id, description) VALUES('IG00', 'geotechnika');
--;;
INSERT INTO fields(id, description) VALUES('IH00', 'požární bezpečnost staveb');
--;;
INSERT INTO fields(id, description) VALUES('II00', 'městské inženýrství');
--;;
INSERT INTO fields(id, description) VALUES('IL00', 'stavby pro plnění funkce lesa');
--;;
INSERT INTO fields(id, description) VALUES('IM00', 'mosty a inženýrské funkce');
--;;
INSERT INTO fields(id, description) VALUES('IP00', 'pozemní stavby');
--;;
INSERT INTO fields(id, description) VALUES('IS00', 'statika a dynamika staveb');
--;;
INSERT INTO fields(id, description) VALUES('IT00', 'technologická zařízení staveb');
--;;
INSERT INTO fields(id, description) VALUES('IV00', 'stavby vodního hospodářství a krajinného inženýrství');
--;;
INSERT INTO fields(id, description) VALUES('IZ00', 'zkoušení a diagnostika staveb');
--;;
INSERT INTO fields(id, description) VALUES('SD01', 'dopravní stavby - kolejová doprava');
--;;
INSERT INTO fields(id, description) VALUES('SD02', 'dopravní stavby - nekolejová doprava');
--;;
INSERT INTO fields(id, description) VALUES('SM00', 'mosty a inženýrské konstrukce');
--;;
INSERT INTO fields(id, description) VALUES('SP00', 'pozemní stavby');
--;;
INSERT INTO fields(id, description) VALUES('SV01', 'stavby vodního hospodářství a krajinného inženýrství - stavby hydrotechnické');
--;;
INSERT INTO fields(id, description) VALUES('SV02', 'stavby vodního hospodářství a krajinného inženýrství - stavby zdravotnětechnické');
--;;
INSERT INTO fields(id, description) VALUES('SV03', 'stavby vodního hospodářství a krajinného inženýrství - stavby meliorační a sanační');
--;;
INSERT INTO fields(id, description) VALUES('TA00', 'energetické auditorství');
--;;
INSERT INTO fields(id, description) VALUES('TD01', 'dopravní stavby - kolejová doprava');
--;;
INSERT INTO fields(id, description) VALUES('TD02', 'dopravní stavby - nekolejová doprava');
--;;
INSERT INTO fields(id, description) VALUES('TE01', 'technika prostředí staveb - vytápění a vzduchotecnika');
--;;
INSERT INTO fields(id, description) VALUES('TE02', 'technika prostředí staveb - zdravotní technika');
--;;
INSERT INTO fields(id, description) VALUES('TE03', 'technika prostředí staveb - elektrotechnická zařízení');
--;;
INSERT INTO fields(id, description) VALUES('TG00', 'geotechnika');
--;;
INSERT INTO fields(id, description) VALUES('TH00', 'požární bezpečnost staveb');
--;;
INSERT INTO fields(id, description) VALUES('TM00', 'mosty a inženýrské konstrukce');
--;;
INSERT INTO fields(id, description) VALUES('TP00', 'pozemní stavby');
--;;
INSERT INTO fields(id, description) VALUES('TT00', 'technologická zařízení staveb');
--;;
INSERT INTO fields(id, description) VALUES('TV01', 'stavby vodního hospodářství a krajinného inženýrství - stavby hydrotechnické');
--;;
INSERT INTO fields(id, description) VALUES('TV02', 'stavby vodního hospodářství a krajinného inženýrství - stavby zdravotnětechnické');
--;;
INSERT INTO fields(id, description) VALUES('TV03', 'stavby vodního hospodářství a krajinného inženýrství - stavby meliorační a sanační');
--;;
